<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cds_en_oferta [
        <!ELEMENT cds_en_oferta (cd)*>
        <!ELEMENT cd (titulo|artista|pais|discografica|precio|year_publicacion)*>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT artista (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
        <!ELEMENT discografica (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT year_publicacion (#PCDATA)>
        ]>
<cds_en_oferta>
    <cd>
        <titulo>Still got the blues</titulo>
        <artista>Gary Moore</artista>
        <pais>UK</pais>
        <discografica>Virgin records</discografica>
        <precio>10.20</precio>
        <year_publicacion>1990</year_publicacion>
    </cd>
    <cd>
        <titulo>One night only</titulo>
        <artista>Bee Gees</artista>
        <pais>UK</pais>
        <discografica>Polydor</discografica>
        <precio>10.90</precio>
        <year_publicacion>1998</year_publicacion>
    </cd>
    <cd>
        <titulo>When a man loves a woman</titulo>
        <artista>Percy Sledge</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>8.70</precio>
        <year_publicacion>1987</year_publicacion>
    </cd>
    <cd>
        <titulo>Big Willie style</titulo>
        <artista>Will Smith</artista>
        <pais>USA</pais>
        <discografica>Columbia</discografica>
        <precio>9.90</precio>
        <year_publicacion>1997</year_publicacion>
    </cd>
    <cd>
        <titulo>La canción de Juan Perro</titulo>
        <artista>Radio Futura</artista>
        <pais>España</pais>
        <discografica>Sony Music-Ariola</discografica>
        <precio>9.90</precio>
        <year_publicacion>1987</year_publicacion>
    </cd>
    <cd>
        <titulo>The dock of the bay</titulo>
        <artista>Otis Redding</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>7.90</precio>
        <year_publicacion>1987</year_publicacion>
    </cd>
</cds_en_oferta>
