<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido [
        <!ELEMENT pedido (destinatario|articulo|direccion|fecha_entrega)*>
        <!ELEMENT destinatario (#PCDATA)>
        <!ELEMENT articulo (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT fecha_entrega (#PCDATA)>
        ]>
<pedido>
    <destinatario>Juan Delgado Mart√≠nez</destinatario>
    <articulo>Bicicleta Bianchi Oltre</articulo>
    <direccion>Calle Reforma 423, tercer piso, letra A</direccion>
    <fecha_entrega>19-09-2021</fecha_entrega>
</pedido>
